name: Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy to Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: npm run build
          # wranglerVersion: "3.75.0"
          command: pages deploy dist --project-name=xbyexample-w
          accountId: ${{ secrets.CF_ACC_ID }}
